version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - craft-code-club/c3-admins
    commit-message:
      prefix: "build"
      include: "scope"
    target-branch: "main"

  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - craft-code-club/c3-admins
    commit-message:
      prefix: "build"
      include: "scope"
    target-branch: "main"

  - package-ecosystem: "docker"
    directories:
      - "**/*" # To specify manifests in the current directory and recursive subdirectories -> https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/controlling-dependencies-updated#defining-multiple-locations-for-manifest-files
    schedule:
      interval: "daily"
    reviewers:
      - craft-code-club/c3-admins
    commit-message:
      prefix: "build"
      include: "scope"
    target-branch: "main"
